POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "userid": "Ramesh",
    "password": "123456"
}

###

GET http://localhost:5000/api/sales/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtcGxveWVlX2lkIjoxLCJuYW1lIjoiUmFtZXNoIiwiZGVwYXJ0bWVudCI6IlNhbGVzIn0sImlhdCI6MTcwMjQzMDE1NCwiZXhwIjoxNzAyNDMzNzU0fQ.WW7QVz_-oeqTdXBcGIC74Uq_AvZV7MD5DKfsLvd2twU


###

GET http://localhost:5000/api/sales/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtcGxveWVlX2lkIjoxLCJuYW1lIjoiUmFtZXNoIiwiZGVwYXJ0bWVudCI6IlNhbGVzIn0sImlhdCI6MTcwMjQzMDE1NCwiZXhwIjoxNzAyNDMzNzU0fQ.WW7QVz_-oeqTdXBcGIC74Uq_AvZV7MD5DKfsLvd2twU

###

GET http://localhost:5000/api/sales/package/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtcGxveWVlX2lkIjoxLCJuYW1lIjoiUmFtZXNoIiwiZGVwYXJ0bWVudCI6IlNhbGVzIn0sImlhdCI6MTcwMjQzMDE1NCwiZXhwIjoxNzAyNDMzNzU0fQ.WW7QVz_-oeqTdXBcGIC74Uq_AvZV7MD5DKfsLvd2twU